version: '3'
services:
  db:
      image: postgres:15.1-alpine
      ports:
        - '${POSTGRES_PORT}:5432'
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_NAME}
