repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: zookeeper
    namespace: doi-production
    chart: ./charts/zookeeper
    values:
      - ./charts/zookeeper/values.yaml
  - name: doi
    namespace: doi-production
    chart: ./charts/doi
    values:
      - ./charts/doi/values.yaml
