apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-it-tomorrow
  labels:
    app: do-it-tomorrow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: do-it-tomorrow
  template:
    metadata:
      labels:
        app: do-it-tomorrow
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
        - name: doi
          image: "{{ .Values.imageRef }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-service-account-key
                  key: data
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
            - name: ZOOKEEPER_CONNECTION_STRING
              value: "zookeeper:2181"
            - name: NEW_SCHEDULER
              value: "true"
            - name: NAMESPACE
              value: "doi-production"
          envFrom:
            - secretRef:
                name: secrets-envs
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
