---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timetriggers-agent-rolebinding
subjects:
  - kind: ServiceAccount
    name: timetriggers-agent-sa
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: timetriggers-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timetriggers-agent-sa
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timetriggers-agent-role
  # "namespace" omitted if was ClusterRoles because are not namespaced
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: ["*"]
    resources:
      - "*"
    verbs:
      - "*"
