name: CI
on: push

jobs:
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/do-it-tomorrow/do-it-tomorrow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: setup docker cli for gcloud
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ format('{0}:{1}', env.IMAGE_NAME, github.sha) }},${{ format('{0}:{1}', env.IMAGE_NAME, 'latest') }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Replace docker cache with new one to save it
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy_kubernetes:
    name: Deploy with helmfile
    runs-on: ubuntu-latest
    needs:
      - build_docker
      - tests
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_TAG: ${{ github.sha }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v1
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.20.2
      - name: Setup kubectl for cluster
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: autopilot-cluster-1
          location: europe-west3
          project_id: "${{ secrets.GOOGLE_PROJECT_ID }}"
      - name: Deploy and wait
        run: helmfile sync

  deploy_fly:
    name: Deploy with fly
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - tests
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run deploy

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run emulators
        run: npm run emulators &
      - name: Run tests
        run: npm test
